apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: jenkins-persistent
  name: jenkins
spec:
  source:
    contextDir: xCI-jenkins
    git:
      uri: https://gitlab.cee.redhat.com/Feuerkasten/xCI-systems.git
      ref: stage
    type: Git
  output:
    to:
      kind: ImageStreamTag
      name: xci-jenkins:latest
  strategy:
    type: Source
    sourceStrategy:
      forcePull: true
      from:
        kind: "DockerImage"
        name: "docker.io/openshift/jenkins-2-centos7:v3.7"
      env:
        - name: GIT_SSL_NO_VERIFY
          value: "true"
  triggers:
  - type: ConfigChange
